---
- name: Install docker
  gather_facts: No
  hosts: dbservers
  become: true
  remote_user: lcars

  tasks:
    - name: Instala yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Instala device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Instala lvm2
      yum:
        name: lvm2
        state: latest

    - name: Adiciona Docker repositorio
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Ativa o repositorio Docker Edge
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Ativa o repositorio Docker Test
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Instala Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Inicia o servico Docker
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Remove imagem antiga
      command:
        cmd: sudo docker rm mysql-mariadb

    - name: Roda imagem Mariadb com senha de root definida
      command:
        cmd: sudo docker run -p 3306:3306 --name mysql-mariadb -e MYSQL_ROOT_PASSWORD=root -d mariadb
